import Head from "next/head";

const Layout = ({ children, pageTitle }) => {
  return (
    <>
      <Head>
        <title>Ahmad Chata - {pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Layout;
