import prisma from "../../lib/prisma";
import React from "react";
import Head from "next/head";
import { GetStaticProps } from "next";
import Post, { PostProps } from "../../components/Post";

export const getStaticProps: GetStaticProps = async () => {
  const feed = await prisma.post.findMany({
    where: { published: true },
    include: {
      author: {
        select: { name: true },
      },
    },
  });
  return {
    props: { feed },
    revalidate: 10,
  };
};

type Props = {
  feed: PostProps[];
};

const Blog: React.FC<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Ahmad Chata - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <section className="center">
          <h1 className="monteya-font orange mb-5 name-heading mt-4">Blog</h1>
          {props.feed.map((post) => (
            <div key={post.id} className="post">
              <Post post={post} />
            </div>
          ))}
        </section>
      </main>
    </>
  );
};

export default Blog;
