import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ahmad Chata - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="d-flex justify-content-center text-center wrapper">
        <section className="content">
          <h1 className="name-heading monteya-font mb-5">
            Hi! I am Ahmad Chata.
          </h1>
          <p className="branch-font short-bio">
            A Full-Stack Developer with passion for clean code. When I am not
            wearing out my not so expensive keyboard, I am either sleeping or
            recreating ideas on pinterest.
          </p>
          <div className="mb-4 socials">
            <a
              className="twitter"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.twitter.com/ahmadchata/"
            >
              <i className="fab fa-twitter"></i>
            </a>
            <a
              className="linkedin"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.linkedin.com/in/ahmadchata/"
            >
              <i className="fab fa-linkedin"></i>
            </a>
            <a
              className="github"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.github.com/ahmadchata/"
            >
              <i className="fab fa-github"></i>
            </a>
          </div>
          {/* <a
            target="_blank"
            rel="noopener noreferrer"
            href="mailto:ahmadchata@gmail.com"
            className="btn rounded-0 btn-lg-sm p-lg-1 px-lg-3 contact-blue me-3"
          >
            Say hi!
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://drive.google.com/file/d/1C9gW_vtJHTBYVsY7IxvIfAzw6rqWBpjx/view?usp=sharing"
            className="btn rounded-0 btn-lg-sm p-lg-1 px-lg-3 contact-blue"
            download=""
          >
            Get my Resume
          </a> */}
        </section>
      </main>
    </>
  );
}
