import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <main>
            <div class="row g-0">
              <div>
                <div class="d-none d-md-flex mb-4">
                  <h3 id="darkMode">
                    <i class="fa-regular fa-moon"></i>
                  </h3>
                </div>
                <div class="slide">
                  <label class="animal" id="animal"></label>
                </div>
                <h1 class="name fs-2">Hi! I am Ahmad Chata.</h1>
                <p class="bio">
                  A Full-Stack Developer with passion for clean code. When I am
                  not wearing out my not so expensive keyboard, I am either
                  sleeping or recreating ideas on pinterest.
                </p>
                <div class="mb-4 socials">
                  <a
                    class="twitter"
                    target="_blank"
                    rel="noopener noreferrer"
                    href="https://www.twitter.com/ahmadchata/"
                  >
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a
                    class="linkedin"
                    target="_blank"
                    rel="noopener noreferrer"
                    href="https://www.linkedin.com/in/ahmadchata/"
                  >
                    <i class="fab fa-linkedin"></i>
                  </a>
                  <a
                    class="github"
                    target="_blank"
                    rel="noopener noreferrer"
                    href="https://www.github.com/ahmadchata/"
                  >
                    <i class="fab fa-github"></i>
                  </a>
                </div>
                <a
                  target="_blank"
                  rel="noopener noreferrer"
                  href="mailto:ahmadchata@gmail.com"
                  class="btn rounded-0 btn-lg-sm p-lg-1 px-lg-3 contact-blue me-3"
                >
                  Say hi!
                </a>
                <a
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://drive.google.com/file/d/1C9gW_vtJHTBYVsY7IxvIfAzw6rqWBpjx/view?usp=sharing"
                  class="btn rounded-0 btn-lg-sm p-lg-1 px-lg-3 contact-blue"
                  download=""
                >
                  Get my Resume
                </a>
              </div>
            </div>
          </main>
        </div>
      </main>
    </>
  );
}
