import Head from "next/head";
import { useState, useEffect, use } from "react";
import BioButtons from "@/components/buttons";
import Bio from "../public/data/bio.json";
import WrittenName from "@/components/writtenName";

export default function Home() {
  const [bio, setBio] = useState();
  const showBio = (e) => {
    setBio(+e.target.id);
  };

  return (
    <>
      <Head>
        <title>Ahmad Chata - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="color-font">
        <section className="center text-center">
          <h1 className="name-heading monteya-font m-0">
            <span className="orange">I am</span> Ahmad Chata
          </h1>

          <p className="branch-font short-bio mb-5">Full-Stack Developer</p>
          <span className="monteya-font">About me</span>
          <span class="arrow mx-2"></span>
          <BioButtons
            buttons={["Short", "Long", "Long ago..."]}
            submit={showBio}
          />
          <p id="demo" className="branch-font show mt-4"></p>
          {bio === 0 && <p className="branch-font show mt-4">{Bio["short"]}</p>}
          {bio === 1 && <p className="branch-font show mt-4">{Bio["long"]}</p>}
          {bio === 2 && (
            <p className="branch-font show mt-4">
              Long ago in a distant land, I Ahmad
            </p>
          )}
          <WrittenName />
          {/* <div className="mb-4 socials">
            <a
              className="twitter"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.twitter.com/ahmadchata/"
            >
              <i className="fab fa-twitter"></i>
            </a>
            <a
              className="linkedin"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.linkedin.com/in/ahmadchata/"
            >
              <i className="fab fa-linkedin"></i>
            </a>
            <a
              className="github"
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.github.com/ahmadchata/"
            >
              <i className="fab fa-github"></i>
            </a>
          </div> */}
        </section>
      </main>
    </>
  );
}
